
import os
import os.path as osp
import argparse


parser = argparse.ArgumentParser()
parser.add_argument("--dryrun", action="store_true")
args = parser.parse_args()

dir_ = 'generated_job_files'
prefix = 'short-unkillable_tasks'

os.makedirs(dir_,exist_ok=True)

for x in os.listdir(dir_):
    if x.startswith(prefix):
        os.remove(osp.join(dir_,x))


commands = ['python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w2048-d3_imagenet-64x64x3         --optimizer sgd         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --benchmark_momentum 0.777 --learning_rate 0.546         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w2048-d3_imagenet-64x64x3         --optimizer adam         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00092 --benchmark_b1 0.9 --benchmark_b2 0.999         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w2048-d3_imagenet-64x64x3         --optimizer adamw         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.000702 --benchmark_b1 0.9 --benchmark_b2 0.95 --benchmark_weight_decay 0.0001         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w2048-d3_imagenet-64x64x3         --optimizer lion         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00017 --benchmark_b1 0.9 --benchmark_b2  0.99 --benchmark_weight_decay 0.1         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w512-d3_imagenet-64x64x3         --optimizer sgd         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --benchmark_momentum 0.777 --learning_rate 0.546         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w512-d3_imagenet-64x64x3         --optimizer adam         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00092 --benchmark_b1 0.9 --benchmark_b2 0.999         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w512-d3_imagenet-64x64x3         --optimizer adamw         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.000702 --benchmark_b1 0.9 --benchmark_b2 0.95 --benchmark_weight_decay 0.0001         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w512-d3_imagenet-64x64x3         --optimizer lion         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00017 --benchmark_b1 0.9 --benchmark_b2  0.99 --benchmark_weight_decay 0.1         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w128-d3_imagenet-64x64x3         --optimizer sgd         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --benchmark_momentum 0.777 --learning_rate 0.546         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w128-d3_imagenet-64x64x3         --optimizer adam         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00092 --benchmark_b1 0.9 --benchmark_b2 0.999         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w128-d3_imagenet-64x64x3         --optimizer adamw         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.000702 --benchmark_b1 0.9 --benchmark_b2 0.95 --benchmark_weight_decay 0.0001         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w128-d3_imagenet-64x64x3         --optimizer lion         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00017 --benchmark_b1 0.9 --benchmark_b2  0.99 --benchmark_weight_decay 0.1         --use_bf16 --seed 1']


for i,c in enumerate(commands):
    content = """#!/bin/bash
#SBATCH --partition=short-unkillable
#SBATCH -J {}_{}
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-task=a100l:1
#SBATCH --cpus-per-task=24
#SBATCH --mem=128G
#SBATCH -t 3:00:00
#SBATCH --mail-user btherien@uwaterloo.ca
#SBATCH --mail-type=END
#SBATCH -o /home/mila/b/benjamin.therien/log/out.%j
#SBATCH -e /home/mila/b/benjamin.therien/log/err.%j

module purge

source /home/mila/b/benjamin.therien/setup.sh

cd /home/mila/b/benjamin.therien/github/learned_aggregation
# source script_new_install.sh
export WANDB_API_KEY=9fa3792d90a05640029b7725e310b9904ac00119


CUDA_VISIBLE_DEVICES=0 {}
""".format(prefix,i,c)

    fn = osp.join(dir_,"{}_{}.sh".format(prefix,i))
    with open(fn,'w') as f:
        f.write(content)


# for x in os.listdir(dir_):
#     if x.startswith(prefix):
#         command = "sbatch " + osp.join(dir_,x)
#         if args.dryrun:
#             print(command)
#         else: 
#             os.system(command)














dir_ = 'generated_job_files'
prefix = 'unkillable_tasks'

os.makedirs(dir_,exist_ok=True)

for x in os.listdir(dir_):
    if x.startswith(prefix):
        os.remove(osp.join(dir_,x))


commands = ['python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 128         --test_project mup-meta-testing         --task transformer-w2048-d3_lm1b-s64-v32k         --optimizer sgd         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --benchmark_momentum 0.777 --learning_rate 0.546         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 128         --test_project mup-meta-testing         --task transformer-w2048-d3_lm1b-s64-v32k         --optimizer adam         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00092 --benchmark_b1 0.9 --benchmark_b2 0.999         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 128         --test_project mup-meta-testing         --task transformer-w2048-d3_lm1b-s64-v32k         --optimizer adamw         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.000702 --benchmark_b1 0.9 --benchmark_b2 0.95 --benchmark_weight_decay 0.0001         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 128         --test_project mup-meta-testing         --task transformer-w2048-d3_lm1b-s64-v32k         --optimizer lion         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00017 --benchmark_b1 0.9 --benchmark_b2  0.99 --benchmark_weight_decay 0.1         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 128         --test_project mup-meta-testing         --task transformer-w1024-d3_lm1b-s64-v32k         --optimizer sgd         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --benchmark_momentum 0.777 --learning_rate 0.546         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 128         --test_project mup-meta-testing         --task transformer-w1024-d3_lm1b-s64-v32k         --optimizer adam         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00092 --benchmark_b1 0.9 --benchmark_b2 0.999         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 128         --test_project mup-meta-testing         --task transformer-w1024-d3_lm1b-s64-v32k         --optimizer adamw         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.000702 --benchmark_b1 0.9 --benchmark_b2 0.95 --benchmark_weight_decay 0.0001         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 128         --test_project mup-meta-testing         --task transformer-w1024-d3_lm1b-s64-v32k         --optimizer lion         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00017 --benchmark_b1 0.9 --benchmark_b2  0.99 --benchmark_weight_decay 0.1         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 128         --test_project mup-meta-testing         --task transformer-w192-d3_lm1b-s64-v32k         --optimizer sgd         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --benchmark_momentum 0.777 --learning_rate 0.546         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 128         --test_project mup-meta-testing         --task transformer-w192-d3_lm1b-s64-v32k         --optimizer adam         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00092 --benchmark_b1 0.9 --benchmark_b2 0.999         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 128         --test_project mup-meta-testing         --task transformer-w192-d3_lm1b-s64-v32k         --optimizer adamw         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.000702 --benchmark_b1 0.9 --benchmark_b2 0.95 --benchmark_weight_decay 0.0001         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 128         --test_project mup-meta-testing         --task transformer-w192-d3_lm1b-s64-v32k         --optimizer lion         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00017 --benchmark_b1 0.9 --benchmark_b2  0.99 --benchmark_weight_decay 0.1         --use_bf16 --seed 1']

for i,c in enumerate(commands):
    content = """#!/bin/bash
#SBATCH --partition=unkillable
#SBATCH -J {}_{}
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-task=a100l:1
#SBATCH --cpus-per-task=6
#SBATCH --mem=32G
#SBATCH -t 48:00:00
#SBATCH --mail-user btherien@uwaterloo.ca
#SBATCH --mail-type=END
#SBATCH -o /home/mila/b/benjamin.therien/log/out.%j
#SBATCH -e /home/mila/b/benjamin.therien/log/err.%j


module purge

source /home/mila/b/benjamin.therien/setup.sh

cd /home/mila/b/benjamin.therien/github/learned_aggregation
# source script_new_install.sh
export WANDB_API_KEY=9fa3792d90a05640029b7725e310b9904ac00119


CUDA_VISIBLE_DEVICES=0 {}
""".format(prefix,i,c)

    fn = osp.join(dir_,"{}_{}.sh".format(prefix,i))
    with open(fn,'w') as f:
        f.write(content)


# for x in os.listdir(dir_):
#     if x.startswith(prefix):
#         command = "sbatch " + osp.join(dir_,x)
#         if args.dryrun:
#             print(command)
#         else: 
#             os.system(command)




















dir_ = 'generated_job_files'
prefix = 'any_tasks'

os.makedirs(dir_,exist_ok=True)

commands = ['python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w8192-d3_imagenet-32x32x3         --optimizer sgd         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --benchmark_momentum 0.777 --learning_rate 0.546         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w8192-d3_imagenet-32x32x3         --optimizer adam         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00092 --benchmark_b1 0.9 --benchmark_b2 0.999         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w8192-d3_imagenet-32x32x3         --optimizer adamw         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.000702 --benchmark_b1 0.9 --benchmark_b2 0.95 --benchmark_weight_decay 0.0001         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w8192-d3_imagenet-32x32x3         --optimizer lion         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00017 --benchmark_b1 0.9 --benchmark_b2  0.99 --benchmark_weight_decay 0.1         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w2048-d3_imagenet-32x32x3         --optimizer sgd         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --benchmark_momentum 0.777 --learning_rate 0.546         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w2048-d3_imagenet-32x32x3         --optimizer adam         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00092 --benchmark_b1 0.9 --benchmark_b2 0.999         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w2048-d3_imagenet-32x32x3         --optimizer adamw         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.000702 --benchmark_b1 0.9 --benchmark_b2 0.95 --benchmark_weight_decay 0.0001         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w2048-d3_imagenet-32x32x3         --optimizer lion         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00017 --benchmark_b1 0.9 --benchmark_b2  0.99 --benchmark_weight_decay 0.1         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w512-d3_imagenet-32x32x3         --optimizer sgd         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --benchmark_momentum 0.777 --learning_rate 0.546         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w512-d3_imagenet-32x32x3         --optimizer adam         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00092 --benchmark_b1 0.9 --benchmark_b2 0.999         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w512-d3_imagenet-32x32x3         --optimizer adamw         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.000702 --benchmark_b1 0.9 --benchmark_b2 0.95 --benchmark_weight_decay 0.0001         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w512-d3_imagenet-32x32x3         --optimizer lion         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00017 --benchmark_b1 0.9 --benchmark_b2  0.99 --benchmark_weight_decay 0.1         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w128-d3_imagenet-32x32x3         --optimizer sgd         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --benchmark_momentum 0.777 --learning_rate 0.546         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w128-d3_imagenet-32x32x3         --optimizer adam         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00092 --benchmark_b1 0.9 --benchmark_b2 0.999         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w128-d3_imagenet-32x32x3         --optimizer adamw         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.000702 --benchmark_b1 0.9 --benchmark_b2 0.95 --benchmark_weight_decay 0.0001         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w128-d3_imagenet-32x32x3         --optimizer lion         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00017 --benchmark_b1 0.9 --benchmark_b2  0.99 --benchmark_weight_decay 0.1         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w2048-d3_imagenet-64x64x3         --optimizer sgd         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --benchmark_momentum 0.777 --learning_rate 0.546         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w2048-d3_imagenet-64x64x3         --optimizer adam         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00092 --benchmark_b1 0.9 --benchmark_b2 0.999         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w2048-d3_imagenet-64x64x3         --optimizer adamw         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.000702 --benchmark_b1 0.9 --benchmark_b2 0.95 --benchmark_weight_decay 0.0001         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w2048-d3_imagenet-64x64x3         --optimizer lion         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00017 --benchmark_b1 0.9 --benchmark_b2  0.99 --benchmark_weight_decay 0.1         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w512-d3_imagenet-64x64x3         --optimizer sgd         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --benchmark_momentum 0.777 --learning_rate 0.546         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w512-d3_imagenet-64x64x3         --optimizer adam         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00092 --benchmark_b1 0.9 --benchmark_b2 0.999         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w512-d3_imagenet-64x64x3         --optimizer adamw         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.000702 --benchmark_b1 0.9 --benchmark_b2 0.95 --benchmark_weight_decay 0.0001         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w512-d3_imagenet-64x64x3         --optimizer lion         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00017 --benchmark_b1 0.9 --benchmark_b2  0.99 --benchmark_weight_decay 0.1         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w128-d3_imagenet-64x64x3         --optimizer sgd         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --benchmark_momentum 0.777 --learning_rate 0.546         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w128-d3_imagenet-64x64x3         --optimizer adam         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00092 --benchmark_b1 0.9 --benchmark_b2 0.999         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w128-d3_imagenet-64x64x3         --optimizer adamw         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.000702 --benchmark_b1 0.9 --benchmark_b2 0.95 --benchmark_weight_decay 0.0001         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w128-d3_imagenet-64x64x3         --optimizer lion         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00017 --benchmark_b1 0.9 --benchmark_b2  0.99 --benchmark_weight_decay 0.1         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w8192-d3_cifar10-32x32x3         --optimizer sgd         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --benchmark_momentum 0.777 --learning_rate 0.546         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w8192-d3_cifar10-32x32x3         --optimizer adam         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00092 --benchmark_b1 0.9 --benchmark_b2 0.999         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w8192-d3_cifar10-32x32x3         --optimizer adamw         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.000702 --benchmark_b1 0.9 --benchmark_b2 0.95 --benchmark_weight_decay 0.0001         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w8192-d3_cifar10-32x32x3         --optimizer lion         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00017 --benchmark_b1 0.9 --benchmark_b2  0.99 --benchmark_weight_decay 0.1         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w2048-d3_cifar10-32x32x3         --optimizer sgd         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --benchmark_momentum 0.777 --learning_rate 0.546         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w2048-d3_cifar10-32x32x3         --optimizer adam         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00092 --benchmark_b1 0.9 --benchmark_b2 0.999         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w2048-d3_cifar10-32x32x3         --optimizer adamw         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.000702 --benchmark_b1 0.9 --benchmark_b2 0.95 --benchmark_weight_decay 0.0001         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w2048-d3_cifar10-32x32x3         --optimizer lion         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00017 --benchmark_b1 0.9 --benchmark_b2  0.99 --benchmark_weight_decay 0.1         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w512-d3_cifar10-32x32x3         --optimizer sgd         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --benchmark_momentum 0.777 --learning_rate 0.546         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w512-d3_cifar10-32x32x3         --optimizer adam         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00092 --benchmark_b1 0.9 --benchmark_b2 0.999         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w512-d3_cifar10-32x32x3         --optimizer adamw         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.000702 --benchmark_b1 0.9 --benchmark_b2 0.95 --benchmark_weight_decay 0.0001         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w512-d3_cifar10-32x32x3         --optimizer lion         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00017 --benchmark_b1 0.9 --benchmark_b2  0.99 --benchmark_weight_decay 0.1         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w128-d3_cifar10-32x32x3         --optimizer sgd         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --benchmark_momentum 0.777 --learning_rate 0.546         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w128-d3_cifar10-32x32x3         --optimizer adam         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00092 --benchmark_b1 0.9 --benchmark_b2 0.999         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w128-d3_cifar10-32x32x3         --optimizer adamw         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.000702 --benchmark_b1 0.9 --benchmark_b2 0.95 --benchmark_weight_decay 0.0001         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w128-d3_cifar10-32x32x3         --optimizer lion         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00017 --benchmark_b1 0.9 --benchmark_b2  0.99 --benchmark_weight_decay 0.1         --use_bf16 --seed 1']

#only 64x64 and c10

commands = ['python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w2048-d3_imagenet-64x64x3         --optimizer sgd         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --benchmark_momentum 0.777 --learning_rate 0.546         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w2048-d3_imagenet-64x64x3         --optimizer adam         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00092 --benchmark_b1 0.9 --benchmark_b2 0.999         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w2048-d3_imagenet-64x64x3         --optimizer adamw         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.000702 --benchmark_b1 0.9 --benchmark_b2 0.95 --benchmark_weight_decay 0.0001         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w2048-d3_imagenet-64x64x3         --optimizer lion         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00017 --benchmark_b1 0.9 --benchmark_b2  0.99 --benchmark_weight_decay 0.1         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w512-d3_imagenet-64x64x3         --optimizer sgd         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --benchmark_momentum 0.777 --learning_rate 0.546         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w512-d3_imagenet-64x64x3         --optimizer adam         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00092 --benchmark_b1 0.9 --benchmark_b2 0.999         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w512-d3_imagenet-64x64x3         --optimizer adamw         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.000702 --benchmark_b1 0.9 --benchmark_b2 0.95 --benchmark_weight_decay 0.0001         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w512-d3_imagenet-64x64x3         --optimizer lion         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00017 --benchmark_b1 0.9 --benchmark_b2  0.99 --benchmark_weight_decay 0.1         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w128-d3_imagenet-64x64x3         --optimizer sgd         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --benchmark_momentum 0.777 --learning_rate 0.546         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w128-d3_imagenet-64x64x3         --optimizer adam         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00092 --benchmark_b1 0.9 --benchmark_b2 0.999         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w128-d3_imagenet-64x64x3         --optimizer adamw         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.000702 --benchmark_b1 0.9 --benchmark_b2 0.95 --benchmark_weight_decay 0.0001         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w128-d3_imagenet-64x64x3         --optimizer lion         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00017 --benchmark_b1 0.9 --benchmark_b2  0.99 --benchmark_weight_decay 0.1         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w8192-d3_cifar10-32x32x3         --optimizer sgd         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --benchmark_momentum 0.777 --learning_rate 0.546         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w8192-d3_cifar10-32x32x3         --optimizer adam         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00092 --benchmark_b1 0.9 --benchmark_b2 0.999         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w8192-d3_cifar10-32x32x3         --optimizer adamw         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.000702 --benchmark_b1 0.9 --benchmark_b2 0.95 --benchmark_weight_decay 0.0001         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w8192-d3_cifar10-32x32x3         --optimizer lion         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00017 --benchmark_b1 0.9 --benchmark_b2  0.99 --benchmark_weight_decay 0.1         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w2048-d3_cifar10-32x32x3         --optimizer sgd         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --benchmark_momentum 0.777 --learning_rate 0.546         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w2048-d3_cifar10-32x32x3         --optimizer adam         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00092 --benchmark_b1 0.9 --benchmark_b2 0.999         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w2048-d3_cifar10-32x32x3         --optimizer adamw         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.000702 --benchmark_b1 0.9 --benchmark_b2 0.95 --benchmark_weight_decay 0.0001         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w2048-d3_cifar10-32x32x3         --optimizer lion         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00017 --benchmark_b1 0.9 --benchmark_b2  0.99 --benchmark_weight_decay 0.1         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w512-d3_cifar10-32x32x3         --optimizer sgd         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --benchmark_momentum 0.777 --learning_rate 0.546         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w512-d3_cifar10-32x32x3         --optimizer adam         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00092 --benchmark_b1 0.9 --benchmark_b2 0.999         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w512-d3_cifar10-32x32x3         --optimizer adamw         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.000702 --benchmark_b1 0.9 --benchmark_b2 0.95 --benchmark_weight_decay 0.0001         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w512-d3_cifar10-32x32x3         --optimizer lion         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00017 --benchmark_b1 0.9 --benchmark_b2  0.99 --benchmark_weight_decay 0.1         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w128-d3_cifar10-32x32x3         --optimizer sgd         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --benchmark_momentum 0.777 --learning_rate 0.546         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w128-d3_cifar10-32x32x3         --optimizer adam         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00092 --benchmark_b1 0.9 --benchmark_b2 0.999         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w128-d3_cifar10-32x32x3         --optimizer adamw         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.000702 --benchmark_b1 0.9 --benchmark_b2 0.95 --benchmark_weight_decay 0.0001         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w128-d3_cifar10-32x32x3         --optimizer lion         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00017 --benchmark_b1 0.9 --benchmark_b2  0.99 --benchmark_weight_decay 0.1         --use_bf16 --seed 1']

commands = ['python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _24task-s_mup_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mumlp-w8192-d3_imagenet-32x32x3         --optimizer mup_small_fc_mlp         --wandb_checkpoint_id eb-lab/mup-meta-training/91hf1o0e         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100          --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _24task-s_mup_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mumlp-w2048-d3_imagenet-32x32x3         --optimizer mup_small_fc_mlp         --wandb_checkpoint_id eb-lab/mup-meta-training/91hf1o0e         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100          --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _24task-s_mup_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mumlp-w512-d3_imagenet-32x32x3         --optimizer mup_small_fc_mlp         --wandb_checkpoint_id eb-lab/mup-meta-training/91hf1o0e         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100          --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _24task-s_mup_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mumlp-w128-d3_imagenet-32x32x3         --optimizer mup_small_fc_mlp         --wandb_checkpoint_id eb-lab/mup-meta-training/91hf1o0e         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100          --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _24task-s_mup_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mumlp-w2048-d3_imagenet-64x64x3         --optimizer mup_small_fc_mlp         --wandb_checkpoint_id eb-lab/mup-meta-training/91hf1o0e         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100          --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _24task-s_mup_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mumlp-w512-d3_imagenet-64x64x3         --optimizer mup_small_fc_mlp         --wandb_checkpoint_id eb-lab/mup-meta-training/91hf1o0e         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100          --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _24task-s_mup_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mumlp-w128-d3_imagenet-64x64x3         --optimizer mup_small_fc_mlp         --wandb_checkpoint_id eb-lab/mup-meta-training/91hf1o0e         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100          --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _24task-s_mup_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mumlp-w8192-d3_cifar10-32x32x3         --optimizer mup_small_fc_mlp         --wandb_checkpoint_id eb-lab/mup-meta-training/91hf1o0e         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100          --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _24task-s_mup_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mumlp-w2048-d3_cifar10-32x32x3         --optimizer mup_small_fc_mlp         --wandb_checkpoint_id eb-lab/mup-meta-training/91hf1o0e         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100          --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _24task-s_mup_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mumlp-w512-d3_cifar10-32x32x3         --optimizer mup_small_fc_mlp         --wandb_checkpoint_id eb-lab/mup-meta-training/91hf1o0e         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100          --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _24task-s_mup_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mumlp-w128-d3_cifar10-32x32x3         --optimizer mup_small_fc_mlp         --wandb_checkpoint_id eb-lab/mup-meta-training/91hf1o0e         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100          --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _24task-s_mup_final         --local_batch_size 128         --test_project mup-meta-testing         --task mutransformer-w2048-d3_lm1b-s64-v32k         --optimizer mup_small_fc_mlp         --wandb_checkpoint_id eb-lab/mup-meta-training/91hf1o0e         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100          --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _24task-s_mup_final         --local_batch_size 128         --test_project mup-meta-testing         --task mutransformer-w1024-d3_lm1b-s64-v32k         --optimizer mup_small_fc_mlp         --wandb_checkpoint_id eb-lab/mup-meta-training/91hf1o0e         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100          --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _24task-s_mup_final         --local_batch_size 128         --test_project mup-meta-testing         --task mutransformer-w192-d3_lm1b-s64-v32k         --optimizer mup_small_fc_mlp         --wandb_checkpoint_id eb-lab/mup-meta-training/91hf1o0e         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100          --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _bs1024_24task-s_mup_final         --local_batch_size 1024         --test_project mup-meta-testing         --task muvit-w2048-d3_imagenet-32x32x3         --optimizer mup_small_fc_mlp         --wandb_checkpoint_id eb-lab/mup-meta-training/91hf1o0e         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100          --use_bf16 --seed 10',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _bs1024_24task-s_mup_final         --local_batch_size 1024         --test_project mup-meta-testing         --task muvit-w1024-d3_imagenet-32x32x3         --optimizer mup_small_fc_mlp         --wandb_checkpoint_id eb-lab/mup-meta-training/91hf1o0e         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100          --use_bf16 --seed 10',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _bs1024_24task-s_mup_final         --local_batch_size 1024         --test_project mup-meta-testing         --task muvit-w192-d3_imagenet-32x32x3         --optimizer mup_small_fc_mlp         --wandb_checkpoint_id eb-lab/mup-meta-training/91hf1o0e         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100          --use_bf16 --seed 10']


commands = ['python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _bs1024_m_sp_final         --local_batch_size 1024         --test_project mup-meta-testing         --task vit-w2048-d3_imagenet-32x32x3         --optimizer sgd         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --benchmark_momentum 0.777 --learning_rate 0.546         --use_bf16 --seed 10',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _bs1024_m_sp_final         --local_batch_size 1024         --test_project mup-meta-testing         --task vit-w2048-d3_imagenet-32x32x3         --optimizer adam         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00092 --benchmark_b1 0.9 --benchmark_b2 0.999         --use_bf16 --seed 10',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _bs1024_m_sp_final         --local_batch_size 1024         --test_project mup-meta-testing         --task vit-w2048-d3_imagenet-32x32x3         --optimizer adamw         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.000702 --benchmark_b1 0.9 --benchmark_b2 0.95 --benchmark_weight_decay 0.0001         --use_bf16 --seed 10',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _bs1024_m_sp_final         --local_batch_size 1024         --test_project mup-meta-testing         --task vit-w2048-d3_imagenet-32x32x3         --optimizer lion         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00017 --benchmark_b1 0.9 --benchmark_b2  0.99 --benchmark_weight_decay 0.1         --use_bf16 --seed 10',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _bs1024_m_sp_final         --local_batch_size 1024         --test_project mup-meta-testing         --task vit-w1024-d3_imagenet-32x32x3         --optimizer sgd         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --benchmark_momentum 0.777 --learning_rate 0.546         --use_bf16 --seed 10',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _bs1024_m_sp_final         --local_batch_size 1024         --test_project mup-meta-testing         --task vit-w1024-d3_imagenet-32x32x3         --optimizer adam         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00092 --benchmark_b1 0.9 --benchmark_b2 0.999         --use_bf16 --seed 10',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _bs1024_m_sp_final         --local_batch_size 1024         --test_project mup-meta-testing         --task vit-w1024-d3_imagenet-32x32x3         --optimizer adamw         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.000702 --benchmark_b1 0.9 --benchmark_b2 0.95 --benchmark_weight_decay 0.0001         --use_bf16 --seed 10',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _bs1024_m_sp_final         --local_batch_size 1024         --test_project mup-meta-testing         --task vit-w1024-d3_imagenet-32x32x3         --optimizer lion         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00017 --benchmark_b1 0.9 --benchmark_b2  0.99 --benchmark_weight_decay 0.1         --use_bf16 --seed 10',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _bs1024_m_sp_final         --local_batch_size 1024         --test_project mup-meta-testing         --task vit-w192-d3_imagenet-32x32x3         --optimizer sgd         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --benchmark_momentum 0.777 --learning_rate 0.546         --use_bf16 --seed 10',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _bs1024_m_sp_final         --local_batch_size 1024         --test_project mup-meta-testing         --task vit-w192-d3_imagenet-32x32x3         --optimizer adam         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00092 --benchmark_b1 0.9 --benchmark_b2 0.999         --use_bf16 --seed 10',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _bs1024_m_sp_final         --local_batch_size 1024         --test_project mup-meta-testing         --task vit-w192-d3_imagenet-32x32x3         --optimizer adamw         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.000702 --benchmark_b1 0.9 --benchmark_b2 0.95 --benchmark_weight_decay 0.0001         --use_bf16 --seed 10',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _bs1024_m_sp_final         --local_batch_size 1024         --test_project mup-meta-testing         --task vit-w192-d3_imagenet-32x32x3         --optimizer lion         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00017 --benchmark_b1 0.9 --benchmark_b2  0.99 --benchmark_weight_decay 0.1         --use_bf16 --seed 10']

commands = ['python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w2048-d3_imagenet-64x64x3         --optimizer sgd         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --benchmark_momentum 0.777 --learning_rate 0.546         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w2048-d3_imagenet-64x64x3         --optimizer adam         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00092 --benchmark_b1 0.9 --benchmark_b2 0.999         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w2048-d3_imagenet-64x64x3         --optimizer adamw         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.000702 --benchmark_b1 0.9 --benchmark_b2 0.95 --benchmark_weight_decay 0.0001         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w2048-d3_imagenet-64x64x3         --optimizer lion         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00017 --benchmark_b1 0.9 --benchmark_b2  0.99 --benchmark_weight_decay 0.1         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w512-d3_imagenet-64x64x3         --optimizer sgd         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --benchmark_momentum 0.777 --learning_rate 0.546         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w512-d3_imagenet-64x64x3         --optimizer adam         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00092 --benchmark_b1 0.9 --benchmark_b2 0.999         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w512-d3_imagenet-64x64x3         --optimizer adamw         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.000702 --benchmark_b1 0.9 --benchmark_b2 0.95 --benchmark_weight_decay 0.0001         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w512-d3_imagenet-64x64x3         --optimizer lion         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00017 --benchmark_b1 0.9 --benchmark_b2  0.99 --benchmark_weight_decay 0.1         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w128-d3_imagenet-64x64x3         --optimizer sgd         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --benchmark_momentum 0.777 --learning_rate 0.546         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w128-d3_imagenet-64x64x3         --optimizer adam         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00092 --benchmark_b1 0.9 --benchmark_b2 0.999         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w128-d3_imagenet-64x64x3         --optimizer adamw         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.000702 --benchmark_b1 0.9 --benchmark_b2 0.95 --benchmark_weight_decay 0.0001         --use_bf16 --seed 1',
 'python src/main.py         --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py         --name_suffix _m_sp_final         --local_batch_size 4096         --test_project mup-meta-testing         --task mlp-w128-d3_imagenet-64x64x3         --optimizer lion         --wandb_checkpoint_id eb-lab/mup-meta-training/2tfh8kuw         --num_runs 5         --num_inner_steps 5000         --needs_state         --adafac_step_mult 0.01         --gradient_accumulation_steps 1         --test_interval 100 --learning_rate 0.00017 --benchmark_b1 0.9 --benchmark_b2  0.99 --benchmark_weight_decay 0.1         --use_bf16 --seed 1']


for x in os.listdir(dir_):
    if x.startswith(prefix):
        os.remove(osp.join(dir_,x))


for i,c in enumerate(commands):
    content = """#!/bin/bash
#SBATCH --partition=long
#SBATCH -J {}_{}
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-task=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=256G
#SBATCH -t 168:00:00
#SBATCH --mail-user btherien@uwaterloo.ca
#SBATCH --mail-type=END
#SBATCH -o /home/mila/b/benjamin.therien/log/out.%j
#SBATCH -e /home/mila/b/benjamin.therien/log/err.%j

module purge

source /home/mila/b/benjamin.therien/setup.sh

cd /home/mila/b/benjamin.therien/github/learned_aggregation
# source script_new_install.sh
export WANDB_API_KEY=9fa3792d90a05640029b7725e310b9904ac00119


CUDA_VISIBLE_DEVICES=0 {}
""".format(prefix,i,c)

    fn = osp.join(dir_,"{}_{}.sh".format(prefix,i))
    with open(fn,'w') as f:
        f.write(content)


for x in os.listdir(dir_):
    if x.startswith(prefix):
        command = "sbatch " + osp.join(dir_,x)
        if args.dryrun:
            print(command)
        else: 
            os.system(command)




